?start: atom

?sum: product
    | sum "+" product         -> add
    | sum "-" product         -> sub

?product: atom
    | product "*" atom        -> mul
    | product "/" atom        -> div

?atom: SIGNED_INT [unit]   -> number
     | "-" atom               -> neg
     | "(" sum ")"          // -> sub_eval // uncomment to have () add new layers

?unit: UNIT -> unit

UNIT: "h" | "w" | "H" | "W"

%import common.SIGNED_INT
%import common.WS_INLINE

%ignore WS_INLINE